package parchment

// Tests for the alias system: UUID id + human-readable mutable alias.

import (
	"context"
	"strings"
	"testing"
)

func uuidProto(t *testing.T) *Protocol {
	t.Helper()
	store := NewMemoryStore()
	_ = store.SetScopeKey(context.Background(), "test", "TST", false)
	tpl := PresetScoped()
	return New(store, nil, []string{"test"}, nil, ProtocolConfig{
		IDFormat:   IDFormatUUID,
		IDTemplate: &tpl,
	})
}

// TestAlias_AutoGeneratedOnCreate verifies that a scope-derived alias is
// assigned automatically when creating an artifact in UUID mode.
func TestAlias_AutoGeneratedOnCreate(t *testing.T) {
	t.Parallel()
	proto := uuidProto(t)
	ctx := context.Background()

	art, err := proto.CreateArtifact(ctx, CreateInput{
		Kind:     "task",
		Title:    "My task",
		Scope:    "test",
		Sections: []Section{{Name: "context", Text: "ctx"}},
	})
	if err != nil {
		t.Fatalf("CreateArtifact: %v", err)
	}
	if !IsUUIDShaped(art.ID) {
		t.Errorf("ID %q should be UUID-shaped", art.ID)
	}
	if art.Alias == "" {
		t.Error("alias should be auto-generated, got empty string")
	}
	if !strings.HasPrefix(art.Alias, "TST-") {
		t.Errorf("alias %q should have TST- prefix", art.Alias)
	}
}

// TestAlias_AliasesAreSequential verifies that successive artifacts get
// incrementing alias numbers (TST-TSK-1, TST-TSK-2, …).
func TestAlias_AliasesAreSequential(t *testing.T) {
	t.Parallel()
	proto := uuidProto(t)
	ctx := context.Background()

	a1, err := proto.CreateArtifact(ctx, CreateInput{
		Kind: "task", Title: "First", Scope: "test",
		Sections: []Section{{Name: "context", Text: "ctx"}},
	})
	if err != nil {
		t.Fatal(err)
	}
	a2, err := proto.CreateArtifact(ctx, CreateInput{
		Kind: "task", Title: "Second", Scope: "test",
		Sections: []Section{{Name: "context", Text: "ctx"}},
	})
	if err != nil {
		t.Fatal(err)
	}

	if a1.Alias == a2.Alias {
		t.Errorf("expected distinct aliases, both got %q", a1.Alias)
	}
	if a1.ID == a2.ID {
		t.Errorf("expected distinct UUIDs, both got %q", a1.ID)
	}
}

// TestAlias_CustomAliasOnCreate verifies that a caller-supplied alias is
// honoured instead of auto-generating one.
func TestAlias_CustomAliasOnCreate(t *testing.T) {
	t.Parallel()
	proto := uuidProto(t)
	ctx := context.Background()

	art, err := proto.CreateArtifact(ctx, CreateInput{
		Kind:     "task",
		Title:    "Login bug",
		Scope:    "test",
		Alias:    "login-bug",
		Sections: []Section{{Name: "context", Text: "ctx"}},
	})
	if err != nil {
		t.Fatalf("CreateArtifact: %v", err)
	}
	if art.Alias != "login-bug" {
		t.Errorf("alias = %q, want login-bug", art.Alias)
	}
}

// TestAlias_GetByAlias verifies that GetArtifact resolves human-readable
// aliases transparently, returning the same artifact as a UUID lookup.
func TestAlias_GetByAlias(t *testing.T) {
	t.Parallel()
	proto := uuidProto(t)
	ctx := context.Background()

	art, err := proto.CreateArtifact(ctx, CreateInput{
		Kind:  "task", Title: "Findable", Scope: "test",
		Alias: "find-me",
		Sections: []Section{{Name: "context", Text: "ctx"}},
	})
	if err != nil {
		t.Fatal(err)
	}

	// Lookup by UUID.
	byUUID, err := proto.GetArtifact(ctx, art.ID)
	if err != nil {
		t.Fatalf("GetArtifact by UUID: %v", err)
	}

	// Lookup by alias.
	byAlias, err := proto.GetArtifact(ctx, "find-me")
	if err != nil {
		t.Fatalf("GetArtifact by alias: %v", err)
	}

	if byUUID.ID != byAlias.ID {
		t.Errorf("UUID lookup ID %q != alias lookup ID %q", byUUID.ID, byAlias.ID)
	}
	if byAlias.Alias != "find-me" {
		t.Errorf("alias round-trip: got %q, want find-me", byAlias.Alias)
	}
}

// TestAlias_Rename verifies that SetField("alias", …) changes the alias
// and the artifact remains findable by the new name. The old alias no longer
// resolves, and the UUID is unaffected.
func TestAlias_Rename(t *testing.T) {
	t.Parallel()
	proto := uuidProto(t)
	ctx := context.Background()

	art, err := proto.CreateArtifact(ctx, CreateInput{
		Kind: "task", Title: "Rename me", Scope: "test",
		Alias: "old-name",
		Sections: []Section{{Name: "context", Text: "ctx"}},
	})
	if err != nil {
		t.Fatal(err)
	}
	uuid := art.ID

	// Rename via SetField.
	results, err := proto.SetField(ctx, []string{uuid}, FieldAlias, "new-name")
	if err != nil || len(results) != 1 || results[0].Error != "" {
		t.Fatalf("SetField alias: err=%v results=%+v", err, results)
	}

	// UUID still works.
	got, err := proto.GetArtifact(ctx, uuid)
	if err != nil {
		t.Fatalf("GetArtifact by UUID after rename: %v", err)
	}
	if got.Alias != "new-name" {
		t.Errorf("alias after rename = %q, want new-name", got.Alias)
	}

	// New alias resolves.
	byNew, err := proto.GetArtifact(ctx, "new-name")
	if err != nil {
		t.Fatalf("GetArtifact by new alias: %v", err)
	}
	if byNew.ID != uuid {
		t.Errorf("new alias resolves to %q, want %q", byNew.ID, uuid)
	}
}

// TestAlias_ScopedModeNoAlias verifies that in scoped (non-UUID) mode,
// no alias is generated — the id field IS the human-readable name.
func TestAlias_ScopedModeNoAlias(t *testing.T) {
	t.Parallel()
	store := NewMemoryStore()
	_ = store.SetScopeKey(context.Background(), "test", "TST", false)
	tpl := PresetScoped()
	proto := New(store, nil, []string{"test"}, nil, ProtocolConfig{IDTemplate: &tpl})
	ctx := context.Background()

	art, err := proto.CreateArtifact(ctx, CreateInput{
		Kind: "task", Title: "Scoped task", Scope: "test",
		Sections: []Section{{Name: "context", Text: "ctx"}},
	})
	if err != nil {
		t.Fatal(err)
	}
	if art.Alias != "" {
		t.Errorf("scoped mode should produce no alias, got %q", art.Alias)
	}
	if IsUUIDShaped(art.ID) {
		t.Errorf("scoped mode ID %q should not be UUID-shaped", art.ID)
	}
}

// TestAlias_SQLite_RoundTrip verifies alias persistence and resolution
// against a real SQLite store (not just MemoryStore).
func TestAlias_SQLite_RoundTrip(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	path := t.TempDir() + "/alias.sqlite"

	s, err := OpenSQLite(path)
	if err != nil {
		t.Fatal(err)
	}
	defer s.Close() //nolint:errcheck // deferred close in test

	if err := s.SetScopeKey(ctx, "test", "TST", false); err != nil {
		t.Fatal(err)
	}

	tpl := PresetScoped()
	proto := New(s, nil, []string{"test"}, nil, ProtocolConfig{
		IDFormat:  IDFormatUUID,
		IDTemplate: &tpl,
	})

	art, err := proto.CreateArtifact(ctx, CreateInput{
		Kind: "task", Title: "Persistent alias", Scope: "test",
		Alias: "persistent-one",
		Sections: []Section{{Name: "context", Text: "ctx"}},
	})
	if err != nil {
		t.Fatal(err)
	}

	// Lookup by alias via Protocol (UUID id stored, alias column indexed).
	found, err := proto.GetArtifact(ctx, "persistent-one")
	if err != nil {
		t.Fatalf("GetArtifact by alias: %v", err)
	}
	if found.ID != art.ID {
		t.Errorf("alias resolved to %q, want %q", found.ID, art.ID)
	}

	// Rename and verify.
	_, _ = proto.SetField(ctx, []string{art.ID}, FieldAlias, "persistent-two")
	renamed, err := proto.GetArtifact(ctx, "persistent-two")
	if err != nil {
		t.Fatalf("GetArtifact by new alias: %v", err)
	}
	if renamed.ID != art.ID {
		t.Errorf("renamed alias resolved to %q, want %q", renamed.ID, art.ID)
	}
}
