apiVersion: scribe/v1
kind: Relationship
metadata:
  name: investigation-parent_of-observation
spec:
  from: kind:investigation.investigation
  relation: parent_of
  to: kind:investigation.observation
